from utilityBlocco import stampaListaBlocchi, listaBlocchiTotale, ultimoBlocco, stampaBlocco, stampaHeader, listaUltimiNBlocchi
from utilityTransazioni import getTransazioni, stampaTransazioni, getCoinbase, getCoinbaseDaBlocchi
from utility import toBinary
from utilityMinerMessage import estraiOpReturn, estraiOpReturnJSON, estraiOpReturnDaTransazioni,filtraOpReturnPerBlocco,stampaOpReturnPerBlocco
from tqdm import tqdm


stampaOpReturnPerBlocco(filtraOpReturnPerBlocco(estraiOpReturnDaTransazioni(getCoinbaseDaBlocchi(listaUltimiNBlocchi(5)))))